//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Room.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int CourseID { get; set; }
        public int UserID { get; set; }

        [Display(Name = "Academic Year")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Year is required.")]
        public string Grade { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
